### ISSUE TITLE
Remove HTML entities

### ISSUE THREAD

**Issue by acabal** [nwhetsell/george-macdonald_phantastes#3]
HTML entities are not allowed in epub, please use `clean` to convert them to Unicode characters

**Comment by nwhetsell** [comment]
No HTML entities appear in this repository. (Numeric character references are valid XML.)

**Comment by acabal** [comment]
OK, please replace the numeric character references with their Unicode equivalents. We don't want any numeric or html entities.

**Comment by nwhetsell** [comment]
Disallowing numeric character references doesn’t make a whole lot of sense to me, but this is done as requested. (Commit f90b1291a5826dfc623a94ddf136f3b01768f082 is simply the repository after running https://github.com/standardebooks/tools/blob/master/clean, except for changes to [src/epub/images/palm-mark.svg](https://github.com/nwhetsell/george-macdonald_phantastes/blob/master/src/epub/images/palm-mark.svg), which I discarded.)
