### ISSUE TITLE
Remove em dash before epigraph source

### ISSUE THREAD

**Issue by acabal** [nwhetsell/george-macdonald_phantastes#4]
See typography manual: https://standardebooks.org/contribute/typography#epigraphs

**Comment by nwhetsell** [comment]
I copied the em dash directly from the Structure and Semantics Manual:

<img width="801" alt="screen shot 2017-10-24 at 7 39 02 pm" src="https://user-images.githubusercontent.com/14102861/31973283-164b5608-b8f3-11e7-91b3-0c104e312345.png">

**Comment by acabal** [comment]
OK, that's a typo then and I'll fix it. In the meantime please remove the dashes per the typography manual. Thanks!
