### ISSUE TITLE
content.opf issues

### ISSUE THREAD

**Issue by acabal** [nwhetsell/george-macdonald_phantastes#6]
- Long description needs more detail; think along the lines of a brief Wikipedia entry. Historical context, summation of themes and ideas explored (but without plot spoilers), publication history, maybe brief relevant background on the author.
- Missing producer metadata--information about you. It should be in the content.opf template file, you can copy and paste that from there and put your name in.

**Comment by nwhetsell** [comment]
> Long description needs more detail; think along the lines of a brief Wikipedia entry. Historical context, summation of themes and ideas explored (but without plot spoilers), publication history, maybe brief relevant background on the author.

Sorry, I lack both the time and the interest to compile this information.

> Missing producer metadata--information about you. It should be in the content.opf template file, you can copy and paste that from there and put your name in.

I deliberately omitted this. I would prefer that my name not be included as a producer. If a producer must be included, you can use yourself, or anyone else. If this is a hard requirement – and I’m sorry to put so fine a point on it – then I will simply delete this repository and be done with it.

**Comment by acabal** [comment]
If you really don't want your name on it, then put "An Anonymous Volunteer" in both the metadata and colophon. But note that your name is already all over the commit history, Github issues, and the mailing list, so I don't see how putting it in the metadata is revealing any more than already has been revealed.

**Comment by nwhetsell** [comment]
It’s just my preference.
