### ISSUE TITLE
titlepage.svg issues

### ISSUE THREAD

**Issue by acabal** [nwhetsell/george-macdonald_phantastes#7]
- Canvas is not the correct height. It must be exactly the height of the contents plus some padding. See the art manual for exact dimensions, and you can even copy and paste from a different 2-line title
- Spacing between title and author is not correct; see art manual

**Comment by nwhetsell** [comment]
I tried to address this in commits 2412fe12cb15ce9a2a297640ce70e9e21593972b and a1528bdb3d70b7612862420acfc73da7b31c6035 by basing titlepage.svg on

https://github.com/standardebooks/rudyard-kipling_kim/blob/1ad5c3f7cddd29629e2cc5d051839fab966d31b2/images/titlepage.svg

If it’s still incorrect, please submit a pull request.
