### ISSUE TITLE
Semantics for poems with subsections

### ISSUE THREAD

**Issue by acabal** [nwhetsell/george-macdonald_phantastes#8]
In `chapter-20.xhtml`, the single poem has two sections. There for it should be a single blockquote, with `<section>`s separating them.  Additionally, the semantics and style for the headers has to be updated to be semantic.

This is one of the rare cases when we can divide sections with `<div>`. We can't use `<section>` because those typically require a `<h#>` element and will appear in the ToC. Also `<article>` is not appropriate. So `<div>` it is.

So it should look something like this:

````
<blockquote epub:type="3998:poem">
<div>
<header><p epub:type="z3998:roman">I</p></header>
<p>
<span>...</span>
...
</p>
</div>
<div>
<header><p epub:type="z3998:roman">II</p></header>
etc...
</div>
</blockquote>
````

The headers can be styled with 
`[epub|type~="z3998:poem] header p{ font-variant: small-caps; text-align: center; margin-bottom: 1em; }`

**Comment by nwhetsell** [comment]
> In `chapter-20.xhtml`, the single poem has two sections.

This is introduced as two songs (but I’m treating them as poems) in the preceding paragraph: “The songs they liked best to hear were two which I made for them.” It does not appear to be a single poem with two sections.

**Comment by acabal** [comment]
OK, no problem. In that case you can leave them as styled, except apply the `<header>` pattern and accompanying style.
